=== diegojosealonso/XSD-Practice/ejercicio2/matricula.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="matricula">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="personal" type="tipoPersonal"/>
        <xs:element name="pago"     type="tipoPago"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="tipoPersonal">
    <xs:sequence>
      <xs:element name="dni"             type="xs:string"/>
      <xs:element name="nombre"          type="xs:string"/>
      <xs:element name="titulacion"      type="xs:string"/>
      <xs:element name="curso-academico" type="xs:string"/>
      <xs:element name="domicilios"      type="tipoDomicilios"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoDomicilios">
    <xs:sequence>
      <xs:element name="domicilio" type="tipoDomicilio"
                  minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoDomicilio">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="tipo" type="tipoAtributoTipo" use="required"/>
  </xs:complexType>

  <xs:simpleType name="tipoAtributoTipo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="familiar"/>
      <xs:enumeration value="habitual"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoPago">
    <xs:sequence>
      <xs:element name="tipo_matricula" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== diegojosealonso/XSD-Practice/ejercicio2/matricula.xml
<?xml version="1.0" encoding="UTF-8"?>
<matricula xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="matricula.xsd">

  <personal>
    <dni>99223366M</dni>
    <nombre>Juan Pardo Martín</nombre>
    <titulacion>Ingeniería Informática</titulacion>
    <curso-academico>1997/1998</curso-academico>
    <domicilios>
      <domicilio tipo="familiar">
        <nombre>C/ Principal no1</nombre>
      </domicilio>
      <domicilio tipo="habitual">
        <nombre>C/ Secundaria no2</nombre>
      </domicilio>
    </domicilios>
  </personal>

  <pago>
    <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
  </pago>

</matricula>
